hoistPattern:
  - '*'
hoistedDependencies:
  registry.npmmirror.com/@babel/helper-string-parser/7.23.4:
    '@babel/helper-string-parser': private
  registry.npmmirror.com/@babel/helper-validator-identifier/7.22.20:
    '@babel/helper-validator-identifier': private
  registry.npmmirror.com/@babel/parser/7.23.6:
    '@babel/parser': private
  registry.npmmirror.com/@babel/types/7.23.6:
    '@babel/types': private
  registry.npmmirror.com/@esbuild/aix-ppc64/0.19.12:
    '@esbuild/aix-ppc64': private
  registry.npmmirror.com/@esbuild/android-arm/0.19.12:
    '@esbuild/android-arm': private
  registry.npmmirror.com/@esbuild/android-arm64/0.19.12:
    '@esbuild/android-arm64': private
  registry.npmmirror.com/@esbuild/android-x64/0.19.12:
    '@esbuild/android-x64': private
  registry.npmmirror.com/@esbuild/darwin-arm64/0.19.12:
    '@esbuild/darwin-arm64': private
  registry.npmmirror.com/@esbuild/darwin-x64/0.19.12:
    '@esbuild/darwin-x64': private
  registry.npmmirror.com/@esbuild/freebsd-arm64/0.19.12:
    '@esbuild/freebsd-arm64': private
  registry.npmmirror.com/@esbuild/freebsd-x64/0.19.12:
    '@esbuild/freebsd-x64': private
  registry.npmmirror.com/@esbuild/linux-arm/0.19.12:
    '@esbuild/linux-arm': private
  registry.npmmirror.com/@esbuild/linux-arm64/0.19.12:
    '@esbuild/linux-arm64': private
  registry.npmmirror.com/@esbuild/linux-ia32/0.19.12:
    '@esbuild/linux-ia32': private
  registry.npmmirror.com/@esbuild/linux-loong64/0.19.12:
    '@esbuild/linux-loong64': private
  registry.npmmirror.com/@esbuild/linux-mips64el/0.19.12:
    '@esbuild/linux-mips64el': private
  registry.npmmirror.com/@esbuild/linux-ppc64/0.19.12:
    '@esbuild/linux-ppc64': private
  registry.npmmirror.com/@esbuild/linux-riscv64/0.19.12:
    '@esbuild/linux-riscv64': private
  registry.npmmirror.com/@esbuild/linux-s390x/0.19.12:
    '@esbuild/linux-s390x': private
  registry.npmmirror.com/@esbuild/linux-x64/0.19.12:
    '@esbuild/linux-x64': private
  registry.npmmirror.com/@esbuild/netbsd-x64/0.19.12:
    '@esbuild/netbsd-x64': private
  registry.npmmirror.com/@esbuild/openbsd-x64/0.19.12:
    '@esbuild/openbsd-x64': private
  registry.npmmirror.com/@esbuild/sunos-x64/0.19.12:
    '@esbuild/sunos-x64': private
  registry.npmmirror.com/@esbuild/win32-arm64/0.19.12:
    '@esbuild/win32-arm64': private
  registry.npmmirror.com/@esbuild/win32-ia32/0.19.12:
    '@esbuild/win32-ia32': private
  registry.npmmirror.com/@esbuild/win32-x64/0.19.12:
    '@esbuild/win32-x64': private
  registry.npmmirror.com/@interactjs/types/1.10.26:
    '@interactjs/types': private
  registry.npmmirror.com/@jridgewell/sourcemap-codec/1.4.15:
    '@jridgewell/sourcemap-codec': private
  registry.npmmirror.com/@rollup/rollup-android-arm-eabi/4.9.6:
    '@rollup/rollup-android-arm-eabi': private
  registry.npmmirror.com/@rollup/rollup-android-arm64/4.9.6:
    '@rollup/rollup-android-arm64': private
  registry.npmmirror.com/@rollup/rollup-darwin-arm64/4.9.6:
    '@rollup/rollup-darwin-arm64': private
  registry.npmmirror.com/@rollup/rollup-darwin-x64/4.9.6:
    '@rollup/rollup-darwin-x64': private
  registry.npmmirror.com/@rollup/rollup-linux-arm-gnueabihf/4.9.6:
    '@rollup/rollup-linux-arm-gnueabihf': private
  registry.npmmirror.com/@rollup/rollup-linux-arm64-gnu/4.9.6:
    '@rollup/rollup-linux-arm64-gnu': private
  registry.npmmirror.com/@rollup/rollup-linux-arm64-musl/4.9.6:
    '@rollup/rollup-linux-arm64-musl': private
  registry.npmmirror.com/@rollup/rollup-linux-riscv64-gnu/4.9.6:
    '@rollup/rollup-linux-riscv64-gnu': private
  registry.npmmirror.com/@rollup/rollup-linux-x64-gnu/4.9.6:
    '@rollup/rollup-linux-x64-gnu': private
  registry.npmmirror.com/@rollup/rollup-linux-x64-musl/4.9.6:
    '@rollup/rollup-linux-x64-musl': private
  registry.npmmirror.com/@rollup/rollup-win32-arm64-msvc/4.9.6:
    '@rollup/rollup-win32-arm64-msvc': private
  registry.npmmirror.com/@rollup/rollup-win32-ia32-msvc/4.9.6:
    '@rollup/rollup-win32-ia32-msvc': private
  registry.npmmirror.com/@rollup/rollup-win32-x64-msvc/4.9.6:
    '@rollup/rollup-win32-x64-msvc': private
  registry.npmmirror.com/@trysound/sax/0.2.0:
    '@trysound/sax': private
  registry.npmmirror.com/@types/estree/1.0.5:
    '@types/estree': private
  registry.npmmirror.com/@vue/compiler-core/3.4.15:
    '@vue/compiler-core': private
  registry.npmmirror.com/@vue/compiler-dom/3.4.15:
    '@vue/compiler-dom': private
  registry.npmmirror.com/@vue/compiler-sfc/3.4.15:
    '@vue/compiler-sfc': private
  registry.npmmirror.com/@vue/compiler-ssr/3.4.15:
    '@vue/compiler-ssr': private
  registry.npmmirror.com/@vue/reactivity/3.4.15:
    '@vue/reactivity': private
  registry.npmmirror.com/@vue/runtime-core/3.4.15:
    '@vue/runtime-core': private
  registry.npmmirror.com/@vue/runtime-dom/3.4.15:
    '@vue/runtime-dom': private
  registry.npmmirror.com/@vue/server-renderer/3.4.15_vue@3.4.15:
    '@vue/server-renderer': private
  registry.npmmirror.com/@vue/shared/3.4.15:
    '@vue/shared': private
  registry.npmmirror.com/boolbase/1.0.0:
    boolbase: private
  registry.npmmirror.com/commander/7.2.0:
    commander: private
  registry.npmmirror.com/css-select/5.1.0:
    css-select: private
  registry.npmmirror.com/css-tree/2.3.1:
    css-tree: private
  registry.npmmirror.com/css-what/6.1.0:
    css-what: private
  registry.npmmirror.com/csso/5.0.5:
    csso: private
  registry.npmmirror.com/csstype/3.1.3:
    csstype: private
  registry.npmmirror.com/dom-serializer/2.0.0:
    dom-serializer: private
  registry.npmmirror.com/domelementtype/2.3.0:
    domelementtype: private
  registry.npmmirror.com/domhandler/5.0.3:
    domhandler: private
  registry.npmmirror.com/domutils/3.1.0:
    domutils: private
  registry.npmmirror.com/entities/4.5.0:
    entities: private
  registry.npmmirror.com/esbuild/0.19.12:
    esbuild: private
  registry.npmmirror.com/estree-walker/2.0.2:
    estree-walker: private
  registry.npmmirror.com/fsevents/2.3.3:
    fsevents: private
  registry.npmmirror.com/magic-string/0.30.5:
    magic-string: private
  registry.npmmirror.com/mdn-data/2.0.30:
    mdn-data: private
  registry.npmmirror.com/nanoid/3.3.7:
    nanoid: private
  registry.npmmirror.com/nth-check/2.1.1:
    nth-check: private
  registry.npmmirror.com/picocolors/1.0.0:
    picocolors: private
  registry.npmmirror.com/postcss/8.4.33:
    postcss: private
  registry.npmmirror.com/rollup/4.9.6:
    rollup: private
  registry.npmmirror.com/source-map-js/1.0.2:
    source-map-js: private
  registry.npmmirror.com/svgo/3.2.0:
    svgo: private
  registry.npmmirror.com/to-fast-properties/2.0.0:
    to-fast-properties: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@7.17.1
pendingBuilds: []
prunedAt: Wed, 24 Jan 2024 09:55:56 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: http://registry.npm.taobao.org/
skipped:
  - registry.npmmirror.com/@esbuild/aix-ppc64/0.19.12
  - registry.npmmirror.com/@esbuild/android-arm/0.19.12
  - registry.npmmirror.com/@esbuild/android-arm64/0.19.12
  - registry.npmmirror.com/@esbuild/android-x64/0.19.12
  - registry.npmmirror.com/@esbuild/darwin-arm64/0.19.12
  - registry.npmmirror.com/@esbuild/darwin-x64/0.19.12
  - registry.npmmirror.com/@esbuild/freebsd-arm64/0.19.12
  - registry.npmmirror.com/@esbuild/freebsd-x64/0.19.12
  - registry.npmmirror.com/@esbuild/linux-arm/0.19.12
  - registry.npmmirror.com/@esbuild/linux-arm64/0.19.12
  - registry.npmmirror.com/@esbuild/linux-ia32/0.19.12
  - registry.npmmirror.com/@esbuild/linux-loong64/0.19.12
  - registry.npmmirror.com/@esbuild/linux-mips64el/0.19.12
  - registry.npmmirror.com/@esbuild/linux-ppc64/0.19.12
  - registry.npmmirror.com/@esbuild/linux-riscv64/0.19.12
  - registry.npmmirror.com/@esbuild/linux-s390x/0.19.12
  - registry.npmmirror.com/@esbuild/linux-x64/0.19.12
  - registry.npmmirror.com/@esbuild/netbsd-x64/0.19.12
  - registry.npmmirror.com/@esbuild/openbsd-x64/0.19.12
  - registry.npmmirror.com/@esbuild/sunos-x64/0.19.12
  - registry.npmmirror.com/@esbuild/win32-arm64/0.19.12
  - registry.npmmirror.com/@esbuild/win32-ia32/0.19.12
  - registry.npmmirror.com/@rollup/rollup-android-arm-eabi/4.9.6
  - registry.npmmirror.com/@rollup/rollup-android-arm64/4.9.6
  - registry.npmmirror.com/@rollup/rollup-darwin-arm64/4.9.6
  - registry.npmmirror.com/@rollup/rollup-darwin-x64/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-arm-gnueabihf/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-arm64-gnu/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-arm64-musl/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-riscv64-gnu/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-x64-gnu/4.9.6
  - registry.npmmirror.com/@rollup/rollup-linux-x64-musl/4.9.6
  - registry.npmmirror.com/@rollup/rollup-win32-arm64-msvc/4.9.6
  - registry.npmmirror.com/@rollup/rollup-win32-ia32-msvc/4.9.6
  - registry.npmmirror.com/fsevents/2.3.3
storeDir: C:\Users\yuzhipeng\AppData\Local\pnpm\store\v3
virtualStoreDir: C:\Users\yuzhipeng\Documents\GitHub\boke\node_modules\.pnpm
